apiVersion: v1
kind: ReplicationController
metadata:
  name: microapiteste
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: microapiteste
    spec:
      containers:
        - name: microapiteste
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: microapiteste
spec:
  type: NodePort
  selector:
    app: microapiteste
  ports:
  - port: 3000
    nodePort: 3001

